line-length = 120
indent-width = 4
target-version = "py310"
output-format = "pylint"
select = [
  # Minimum checks
  "F", # https://docs.astral.sh/ruff/rules/#pyflakes-f
  "E", "W", # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
  "I", # https://docs.astral.sh/ruff/rules/#isort-i
  "N", # https://docs.astral.sh/ruff/rules/#pep8-naming-n
  "UP", # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "B", # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
  "SIM", # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
  # Additional checks
  # "PL", # https://docs.astral.sh/ruff/rules/#pylint-pl
  # "YTT", # https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
  # "S", # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
  "COM", # https://docs.astral.sh/ruff/rules/#flake8-commas-com
  # "DTZ", # https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
  # "T10", # https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
  # "ICN", # https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn
  # "PIE", # https://docs.astral.sh/ruff/rules/#flake8-pie-pie
  # "PYI", # https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi
  # "PT", # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
  # "TCH", # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
  # "PGH", # https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh
  # "TRY", # https://docs.astral.sh/ruff/rules/#tryceratops-try
  # "NPY", # https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy
  # "FURB", # https://docs.astral.sh/ruff/rules/#refurb-furb
  # "LOG", # https://docs.astral.sh/ruff/rules/#flake8-logging-log
  # "PERF", # https://docs.astral.sh/ruff/rules/#perflint-perf
  # "C90", # https://docs.astral.sh/ruff/rules/#mccabe-c90
  # "D", # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  # "FBT", # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
  # "A", # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
  # "C4", # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
  # "FLY", # https://docs.astral.sh/ruff/rules/#flynt-fly
  # "TCH", # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
  # "RUF", # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
]
# https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/
ignore = ["F541"]

[per-file-ignores]
# https://docs.astral.sh/ruff/rules/unused-import/
# https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/
"__init__.py" = ["F401", "E402"]
